import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Animate from '../components/ui/animate'
import { supabase } from '../helper/db'
import { useEffect } from 'react'
import {updateUser} from '../helper/functions'
import UserLayout from '../components/user/userlayout'
import { useglobal } from '../context'
export default function Home() {


const {name} = useglobal();



  const authuser =  supabase.auth.user();
  console.log('authuser', authuser)

useEffect(() => {

 authuser && updateUser(authuser)


}, [authuser])

// update users table with authuser data if verified

// const updateUser = async () => {

//   if (authuser?.id) {
// console.log('executing updateUser')
//   const { user, error } = await supabase.from('users').update({
//     verified: true,

// }).eq('id', authuser.id)
// console.log('updateUser', user, error)
//   }

// }



  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  <UserLayout>
<div>
  home page here
  {name}
</div>

  </UserLayout>



    </div>
  )
}
