import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Animate from '../components/ui/animate'
import { supabase } from '../helper/db'
import { useEffect,useState } from 'react'
import {updateUser ,findUser ,fetchProducts } from '../helper/functions'
import UserLayout from '../components/user/userlayout'
import { useglobal } from '../context'

export default function Home() {


const {name ,   setUserinfo,userinfo,  } = useglobal();
const [products, setProducts] = useState([])


  const authuser =  supabase.auth.user();
 // console.log('authuser', authuser)

useEffect(() => {

 authuser && updateUser(authuser)
  authuser && findUser(authuser).then(user => {
    setUserinfo(user)
   // console.log('userinfo is ----->', user)
    

  })

  fetchProducts().then(res => {
 
 
    
    setProducts(res)
    console.log('products is ⏺⏺⏺ ----->', products)
   
  })

}, [authuser])







  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  <UserLayout>
<div>





</div>

  </UserLayout>



    </div>
  )
}
